# Generated by Django 4.2.7 on 2024-02-26 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_profile_remove_schedule_cat_remove_schedule_user_and_more"),
        ("core", "0002_task_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="diary",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="user",
        ),
        migrations.RemoveField(
            model_name="task",
            name="duration",
        ),
        migrations.AddField(
            model_name="diary",
            name="cat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.cat",
            ),
        ),
        migrations.AddField(
            model_name="diary",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="diary",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="diary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="diary",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="diary",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="cat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.cat",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="cat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.cat",
            ),
        ),
    ]
