# Generated by Django 4.2.7 on 2024-03-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_diary_cat_alter_diary_date_alter_diary_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="event",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="cat",
        ),
        migrations.RemoveField(
            model_name="task",
            name="cat",
        ),
        migrations.AlterField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="完了"),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200, verbose_name="タイトル"),
        ),
    ]
