# Generated by Django 4.2.7 on 2024-03-08 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_rename_event_schedule_title_remove_schedule_cat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="date",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="time",
        ),
        migrations.AddField(
            model_name="schedule",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="end_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="schedule",
            name="start_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
