# Generated by Django 4.2.7 on 2024-04-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_schedule_date_remove_schedule_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="owner",
        ),
        migrations.AddField(
            model_name="schedule",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_datetime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_datetime",
            field=models.DateTimeField(),
        ),
    ]
