# Generated by Django 4.2.7 on 2024-04-09 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_schedule_reminder_sent_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="reminder_sent",
        ),
        migrations.AddField(
            model_name="schedule",
            name="category_color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="schedule",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="reminder",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
