# Generated by Django 4.2.7 on 2024-05-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_schedule_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="duration",
            field=models.DurationField(blank=True, null=True, verbose_name="期間"),
        ),
    ]
