# Generated by Django 4.2.7 on 2024-05-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_task_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="duration",
            field=models.DurationField(blank=True, null=True, verbose_name="時間"),
        ),
    ]
