# Generated by Django 4.2.7 on 2024-03-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_cat_birthday_cat_food_amount_cat_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "オス"), ("female", "メス")],
                max_length=6,
                null=True,
            ),
        ),
    ]
