# Generated by Django 4.2.7 on 2024-03-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_cat_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cat_photos/"),
        ),
    ]
